#!/usr/bin/env bash

if
  [[ -s "/home/daniel/Applications/twitter-search/iteration-3/.gs/environment" ]]
then
  source "/home/daniel/Applications/twitter-search/iteration-3/.gs/environment"
  exec erb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/daniel/Applications/twitter-search/iteration-3/.gs/environment'" >&2
  exit 1
fi
